spring:
  freemarker:
    # 设置是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
    allow-request-override: false
    # 关闭缓存, 热启动 方便本地调试(build 后刷新界面即可), 上生产改为 true
    cache: false
    #检查模板位置是否存在。
    check-template-location: true
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: utf-8
    # 设置是否应该在与模板合并之前将所有请求属性添加到模型中。
    expose-request-attributes: false
    # 设置是否在与模板合并之前将所有 HttpSession 属性添加到模型中。
    expose-session-attributes: false
    # 设置是否公开 RequestContext 供 Spring 宏库使用, 名称为"SpringMacroRequestContext"。
    expose-spring-macro-helpers: false
    # 更喜欢文件系统访问模板加载, 文件系统访问允许对模板更改进行热检测。
    prefer-file-system-access: false
    # 设置模板前缀名, 用于在构建 URL 时查看名称
    request-context-attribute: request
    # 众所周知的 FreeMarker 密钥将传递给 FreeMarker 的配置。
    settings:
      number_format: 0.##
    # 所有视图的 RequestContext 属性的名称。
    suffix: .html
    # 设置文件路径, 以逗号分隔的模板路径列表。
    template-loader-path: classpath:/templates/
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**
  # springboot 内置的 Tomcat 默认上传文件大小为 1M, 低版本 springboot 将 servlet 改为 http
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1024MB
      # 总文件大小(允许存储文件的文件夹大小)
      max-request-size: 2048MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/myself_lzc?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root#123QAZ!
    url: jdbc:mysql://11.11.237.201:8066/cms?useUnicode=true&characterEncoding=UTF8&useSSL=FALSE&serverTimezone=Asia/Shanghai
    username: sdp
    password: lajsdhf*^KH@LJHljsdf
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置.
  # Maven 多模块项目的扫描路径需以 classpath*: 开头(即加载多个 jar 包下的 XML 文件)
  mapper-locations: classpath*:mybatis/mapper/*.xml
  global-config:
    db-config:
      # 主键类型
      id-type: auto
      # 全局逻辑删除字段值
      logic-delete-field: is_delete
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 1
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 2
  configuration:
    # 是否开启自动驼峰命名规则映射, 数据库下划线命名列名到 Java 驼峰命名. 数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
    map-underscore-to-camel-case: true
    # Mybatis一级缓存, 默认为 SESSION. 单服务开启可提高性能, 微服务需关闭, 因为同一个session相同查询语句不会再次查询数据库, 产生脏数据
    local-cache-scope: statement  # 关闭一级缓存
    # 开启Mybatis二级缓存, 默认为 true
    cache-enabled: false
    # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

fdfs:
  so-timeout: 1501
  connect-timeout: 601
#  thumb-image:             #缩略图生成参数
#    width: 150
#    height: 150
  tracker-list:            #TrackerList参数,支持多个
#    - 139.224.130.26:22122
    - 11.11.237.205:22122
#  web-server-url: 139.224.130.26:8093/
  web-server-url: 11.11.237.205:8888/
  pool:
    # 连接池最大数量
    max-total: 200
    # 单个tracker最大连接数
    max-total-per-key: 50
    # 连接耗尽最大等待时间(毫秒)
    max-wait-millis: 5000

common:
  file:
    native:
      fileUploadTempDir: /Users/liuzhichao/fileupload
      fileUploadDir: /Users/liuzhichao/fileupload
    web:
      SlicesUploadUrl: http://localhost:8090/api/file/SlicesUpload
      SlicesDownloadUrl: http://localhost:8090/api/file/SlicesDownload


# springboot 项目界面默认存放在 static 下面, 配置路径时省略 static 即可.
#spring:
#  mvc:
#    view:
#      prefix: /view/
#      suffix: .html